/*
 * Hello Service
 *
 * A hello world service.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"io/ioutil"
	"net/http"
)

// HelloApiService is a service that implements the logic for the HelloApiServicer
// This service should implement the business logic for every endpoint for the HelloApi API.
// Include any external packages or services that will be required by this service.
type HelloApiService struct {
}

// NewHelloApiService creates a default api service
func NewHelloApiService() HelloApiServicer {
	return &HelloApiService{}
}

// HelloHello - hello hello
func (s *HelloApiService) HelloHello(ctx context.Context, name string) (ImplResponse, error) {
	return Response(http.StatusOK, "Hello, "+name+"."), nil
}

// HelloOpenapiJson - Download ./gen/http/openapi.json
func (s *HelloApiService) HelloOpenapiJson(ctx context.Context) (ImplResponse, error) {
	b, err := ioutil.ReadFile("openapi3.json")
	if err != nil {
		return Response(http.StatusInternalServerError, err), err
	}
	return Response(http.StatusOK, string(b)), nil
}
